import { useState, useEffect, useCallback, useRef } from "react";
import { gsap } from "gsap";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// import Swiper core and required modules
import { Navigation } from "swiper";

import FadeIn from "../animation/FadeIn";
import FadeZoomIn from "../animation/FadeZoomIn";
import Moving from "../animation/Moving";
import Mask from "../animation/Mask";

import { Mousewheel, Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

const SECTIONS_COUNT = 9;

const TOKENOMICS_DATA = [
  {
    stage: "SEED ROUND",
    total: "10l",
    quantity: "100,000,000",
    price: "$0.025",
    totalSold: "$2.500.000",
    vestingPeriod: "Cliff 6 Months, 4% Monthly Unlock",
  },
  {
    stage: "PARTNERSHIP",
    total: "4%",
    quantity: "40,000,000",
    price: "$0.027",
    totalSold: "$1.080.000",
    vestingPeriod: "Cliff 6 Months, then 6% Monthly Unlock",
  },
  {
    stage: "PRIVATE ROUND",
    total: "6%",
    quantity: "60,000,000",
    price: "$0.025",
    totalSold: "$1.080.000",
    vestingPeriod:
      "5% five days after TGE, Cliff 1 Month, then 5% Monthly Unlock",
  },
  {
    stage: "PUBLIC ROUND",
    total: "3%",
    quantity: "30,000,000",
    price: "$0.040",
    totalSold: "$1.200.000",
    vestingPeriod: "25% five days after TGE, then 25% Monthly Unlock",
  },
  {
    stage: "CORE TEAM",
    total: "5%",
    quantity: "50,000,000",
    price: "",
    totalSold: "",
    vestingPeriod: "Cliff 12 Months, 4% Monthly Unlock",
  },
  {
    stage: "ADVISOR TEAM",
    total: "3%",
    quantity: "30,000,000",
    price: "",
    totalSold: "",
    vestingPeriod: "3% five days after TGE, Cliff 6 Months, 6% Monthly Unlock",
  },
  {
    stage: "LIQUIDITY",
    total: "9%",
    quantity: "90,000,000",
    price: "",
    totalSold: "",
    vestingPeriod: "40% at TGE, 5% Monthly Unlock",
  },
  {
    stage: "MARKETING",
    total: "28%",
    quantity: "100,000,000",
    price: "",
    totalSold: "",
    vestingPeriod: "2% Monthly Unlock",
  },
  {
    stage: "REWARD POOL",
    total: "28%",
    quantity: "280,000,000",
    price: "",
    totalSold: "",
    vestingPeriod: "Unlocked when P2P releases",
  },
  {
    stage: "STAKING POOL",
    total: "10%",
    quantity: "100,000,000",
    price: "",
    totalSold: "",
    vestingPeriod: "At the TGE",
  },
  {
    stage: "RESERVE",
    total: "12%",
    quantity: "120,000,000",
    price: "",
    totalSold: "",
    vestingPeriod:
      "Cliff 6 Months, Unlock only for raising fund, with announcement,",
  },
];

export default function Home() {
  const el = useRef();

  const [active, setActive] = useState("problem");

  const [isAnimating, setIsAnimating] = useState(false);
  const [activeSection, setActiveSection] = useState(-1);

  const [step, setStep] = useState(-1);

  const scrollTo = (idx, direction) => {
    setIsAnimating(true);
    setStep(idx);
    setActiveSection(-1);

    const anim = gsap.to(el.current, {
      x: 0,
      y: `${-idx * 100}vh`,
      z: 0,
      duration: 1.5,
      onComplete: function () {
        // TODO: Run animate of active section
        setActiveSection(idx);
        setTimeout(() => {
          setIsAnimating(false);
        }, 350);
      },
      // onUpdate: () => {
      //   console.log(anim.time());
      //   if (anim.time() > 0.75) {
      //     setActiveSection(idx);
      //   }
      // },
    });
  };

  const handleOnWheel = (e) => {
    let idx;
    let direction;
    if (e.deltaY < 0) {
      idx = activeSection - 1 > 0 ? activeSection - 1 : 0;
      direction = "up";
    } else if (e.deltaY > 0) {
      idx =
        activeSection + 1 < SECTIONS_COUNT
          ? activeSection + 1
          : SECTIONS_COUNT - 1;
      direction = "down";
    }

    if (idx !== activeSection) {
      if (!isAnimating) {
        scrollTo(idx, direction);
      }
    }
  };

  useEffect(() => {
    setActiveSection(0);
  }, []);

  return (
    <main
      className={`relative w-screen h-screen overflow-hidden ${
        step === 1 ? "step-1" : ""
      } ${step === 2 ? "step-2" : ""} ${step === 3 ? "step-3" : ""} ${
        step === 4 ? "step-4" : ""
      } ${step === 5 ? "step-5" : ""} ${step === 6 ? "step-6" : ""} ${
        step === 7 ? "step-7" : ""
      } ${step === 8 ? "step-8" : ""}`}
      style={{
        backgroundImage: "url(/bg-dot.png)",
      }}
    >
      <Head>
        <title>Vilik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a
        href="#"
        title="Vilik"
        className="fixed top-[1.66666667vw] left-[1.66666667vw] z-50"
      >
        <svg
          width="157"
          height="38"
          viewBox="0 0 157 38"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M23.0859 19.6962L31.7748 37.9992L0 19.6962H23.0859ZM31.7748 0L0 18.3031H23.0859L31.7748 0ZM27.5888 18.9996C27.5888 15.4531 29.6814 12.4127 32.6623 10.9567V1.3931L24.291 18.9996L32.5993 36.6061V27.0434C29.6822 25.5865 27.5888 22.5461 27.5888 18.9996ZM36.4685 11.5265C35.5802 11.5265 34.7558 11.6532 33.9951 11.9696C33.4876 12.1593 33.0438 12.3498 32.6001 12.6032C30.3805 13.9333 28.9216 16.3401 28.9216 19.0634C28.9216 21.7866 30.3805 24.1934 32.6001 25.5235C33.0438 25.777 33.4883 25.9667 33.9951 26.1571C34.7565 26.4105 35.581 26.6002 36.4685 26.6002C37.3567 26.6002 38.1812 26.4735 38.9418 26.1571C39.4494 25.9674 39.8931 25.777 40.3369 25.5235C42.5564 24.1934 44.0153 21.7866 44.0153 19.0634C44.0153 16.3401 42.5564 13.9333 40.3369 12.6032C39.8931 12.3498 39.4486 12.1601 38.9418 11.9696C38.1804 11.6532 37.356 11.5265 36.4685 11.5265ZM49.9141 19.6962H73L41.2252 38L49.9141 19.6962ZM73 18.3031L41.2252 0L49.851 18.3031H73ZM45.4112 18.9996C45.4112 22.5461 43.3186 25.5865 40.3377 27.0426V36.6691L48.709 18.9996L40.3369 1.3931V11.0196C43.3178 12.4135 45.4112 15.4531 45.4112 18.9996Z"
            fill="url(#paint0_linear_890_4442)"
          />
          <path
            d="M91.2423 9.60449H93.8673C94.0529 9.60449 94.2649 9.7368 94.3445 9.92203L99.4885 21.0393C99.5946 21.251 99.7006 21.3568 99.8066 21.3568C99.9126 21.3568 100.019 21.251 100.125 21.0393L105.242 9.92203C105.322 9.7368 105.534 9.60449 105.746 9.60449H108.344C108.556 9.60449 108.636 9.7368 108.556 9.92203L100.178 28.16C100.098 28.3187 99.9656 28.3981 99.8066 28.3981C99.6476 28.3981 99.4885 28.3187 99.409 28.16L91.0302 9.92203C90.9507 9.7368 91.0302 9.60449 91.2423 9.60449Z"
            fill="url(#paint1_linear_890_4442)"
          />
          <path
            d="M111.66 9.94849C111.66 9.7368 111.792 9.60449 112.004 9.60449H114.497C114.709 9.60449 114.841 9.7368 114.841 9.94849V12.225C114.841 12.4367 114.709 12.569 114.497 12.569H112.004C111.792 12.569 111.66 12.4367 111.66 12.225V9.94849Z"
            fill="url(#paint2_linear_890_4442)"
          />
          <path
            d="M112.004 15.1367H114.497C114.709 15.1367 114.841 15.269 114.841 15.4807V27.7896C114.841 28.0013 114.709 28.1336 114.497 28.1336H112.004C111.792 28.1336 111.66 28.0013 111.66 27.7896V15.4807C111.66 15.269 111.792 15.1367 112.004 15.1367Z"
            fill="url(#paint3_linear_890_4442)"
          />
          <path
            d="M133.853 9.94849C133.853 9.7368 133.985 9.60449 134.197 9.60449H136.69C136.902 9.60449 137.034 9.7368 137.034 9.94849V12.225C137.034 12.4367 136.902 12.569 136.69 12.569H134.197C133.985 12.569 133.853 12.4367 133.853 12.225V9.94849Z"
            fill="url(#paint4_linear_890_4442)"
          />
          <path
            d="M122.054 9.94849C122.054 9.7368 121.921 9.60449 121.709 9.60449H119.217C119.005 9.60449 118.872 9.7368 118.872 9.94849V22.2018H122.054V9.94849Z"
            fill="url(#paint5_linear_890_4442)"
          />
          <path
            d="M130.539 25.1677H122.796C122.774 25.1677 122.752 25.1668 122.731 25.165H118.872V27.7882C118.872 27.9999 119.005 28.1322 119.217 28.1322H130.539C130.751 28.1322 130.883 27.9999 130.883 27.7882V25.5117C130.883 25.3009 130.751 25.1677 130.539 25.1677Z"
            fill="url(#paint6_linear_890_4442)"
          />
          <path
            d="M134.197 15.1367H136.69C136.902 15.1367 137.034 15.269 137.034 15.4807V27.7896C137.034 28.0013 136.902 28.1336 136.69 28.1336H134.197C133.985 28.1336 133.853 28.0013 133.853 27.7896V15.4807C133.853 15.269 133.985 15.1367 134.197 15.1367Z"
            fill="url(#paint7_linear_890_4442)"
          />
          <path
            d="M154.508 9.86803L152.651 12.1931L152.65 12.194L148.663 17.174L146.355 20.0547C146.322 20.0865 146.291 20.1226 146.26 20.165L145.926 20.591L144.722 22.1231C144.43 22.468 144.245 22.9972 144.245 23.447V27.7884C144.245 28.0001 144.113 28.1324 143.9 28.1324H141.407C141.195 28.1324 141.062 28.0001 141.062 27.7884V9.9483C141.062 9.73573 141.195 9.60342 141.407 9.60342H143.9C144.113 9.60342 144.245 9.73573 144.245 9.9483V17.2798C144.245 17.5444 144.297 17.6503 144.404 17.6503C144.484 17.6503 144.59 17.5973 144.722 17.4386L145.012 17.0778L148.874 12.2628L150.135 10.691L150.795 9.86715C150.927 9.70838 151.139 9.60254 151.352 9.60254H154.375C154.587 9.60342 154.64 9.71015 154.508 9.86803Z"
            fill="url(#paint8_linear_890_4442)"
          />
          <path
            d="M145.927 20.592L146.357 20.0566C146.324 20.0884 146.292 20.1246 146.262 20.166L145.927 20.592Z"
            fill="#D3AEF4"
          />
          <path
            d="M156.947 27.8693L149.87 18.7217L148.588 20.3067L147.916 21.1385L153.101 27.8702C153.233 28.029 153.445 28.1348 153.657 28.1348H156.786C157 28.1339 157.053 28.0281 156.947 27.8693Z"
            fill="url(#paint9_linear_890_4442)"
          />
          <defs>
            <linearGradient
              id="paint0_linear_890_4442"
              x1="0"
              y1="18.9998"
              x2="73.0001"
              y2="18.9998"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#05DAC5" />
              <stop offset="0.3585" stopColor="#5C6AF3" />
              <stop offset="0.499" stopColor="#8F74D9" />
              <stop offset="0.6491" stopColor="#CC42D3" />
              <stop offset="1" stopColor="#FC176F" />
            </linearGradient>
            <linearGradient
              id="paint1_linear_890_4442"
              x1="99.7936"
              y1="9.60408"
              x2="99.7936"
              y2="28.3979"
              gradientUnits="userSpaceOnUse"
            >
              <stop offset="0.1711" stopColor="#BC79AD" />
              <stop offset="0.7698" stopColor="#8BE3F7" />
            </linearGradient>
            <linearGradient
              id="paint2_linear_890_4442"
              x1="111.564"
              y1="9.55631"
              x2="113.915"
              y2="11.6964"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="white" />
              <stop offset="0.0269" stopColor="#EEF8FA" />
              <stop offset="0.1345" stopColor="#ADDCE6" />
              <stop offset="0.2372" stopColor="#77C5D5" />
              <stop offset="0.332" stopColor="#4DB3C8" />
              <stop offset="0.4173" stopColor="#2FA6BF" />
              <stop offset="0.4902" stopColor="#1D9EB9" />
              <stop offset="0.5419" stopColor="#169BB7" />
            </linearGradient>
            <linearGradient
              id="paint3_linear_890_4442"
              x1="113.251"
              y1="28.1333"
              x2="113.251"
              y2="15.1364"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#8BE3F7" />
              <stop offset="0.322" stopColor="#89E2F6" />
              <stop offset="0.4942" stopColor="#81DDF1" />
              <stop offset="0.6308" stopColor="#73D4EA" />
              <stop offset="0.7488" stopColor="#60C8DF" />
              <stop offset="0.8548" stopColor="#47B9D2" />
              <stop offset="0.9508" stopColor="#29A7C1" />
              <stop offset="1" stopColor="#169BB7" />
            </linearGradient>
            <linearGradient
              id="paint4_linear_890_4442"
              x1="135.443"
              y1="12.5688"
              x2="135.443"
              y2="9.60408"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#4F5BBD" />
              <stop offset="0.3755" stopColor="#515CBD" />
              <stop offset="0.5414" stopColor="#5862BF" />
              <stop offset="0.6661" stopColor="#656BC1" />
              <stop offset="0.7701" stopColor="#7777C5" />
              <stop offset="0.8612" stopColor="#8E88C9" />
              <stop offset="0.942" stopColor="#AA9CCF" />
              <stop offset="1" stopColor="#C4AED4" />
            </linearGradient>
            <linearGradient
              id="paint5_linear_890_4442"
              x1="124.366"
              y1="12.0982"
              x2="116.572"
              y2="19.9057"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#4F84BD" />
              <stop offset="0.4162" stopColor="#4F5BBD" />
              <stop offset="1" stopColor="#8BE3F7" />
            </linearGradient>
            <linearGradient
              id="paint6_linear_890_4442"
              x1="118.871"
              y1="26.6491"
              x2="130.883"
              y2="26.6491"
              gradientUnits="userSpaceOnUse"
            >
              <stop offset="0.0027933" stopColor="#8BE3F7" />
              <stop offset="1" stopColor="#8BE3F7" />
            </linearGradient>
            <linearGradient
              id="paint7_linear_890_4442"
              x1="135.443"
              y1="15.1364"
              x2="135.443"
              y2="28.1333"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#4F5BBD" />
              <stop offset="0.0774" stopColor="#576DC5" />
              <stop offset="0.2827" stopColor="#6997D7" />
              <stop offset="0.4824" stopColor="#78B8E5" />
              <stop offset="0.6728" stopColor="#83D0EF" />
              <stop offset="0.8497" stopColor="#89DEF5" />
              <stop offset="1" stopColor="#8BE3F7" />
            </linearGradient>
            <linearGradient
              id="paint8_linear_890_4442"
              x1="144.16"
              y1="24.7871"
              x2="147.733"
              y2="10.1286"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#8BE3F7" />
              <stop offset="0.4332" stopColor="#4F5BBD" />
              <stop offset="0.5039" stopColor="#545FBE" />
              <stop offset="0.5874" stopColor="#6269C1" />
              <stop offset="0.6774" stopColor="#7A7AC5" />
              <stop offset="0.7717" stopColor="#9B91CC" />
              <stop offset="0.866" stopColor="#C4AED4" />
            </linearGradient>
            <linearGradient
              id="paint9_linear_890_4442"
              x1="152.459"
              y1="28.1336"
              x2="152.459"
              y2="18.721"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#8BE3F7" />
              <stop offset="0.3812" stopColor="#8AE1F5" />
              <stop offset="0.5496" stopColor="#88DAEE" />
              <stop offset="0.6761" stopColor="#83CFE1" />
              <stop offset="0.7817" stopColor="#7DBECF" />
              <stop offset="0.8742" stopColor="#75A8B8" />
              <stop offset="0.9562" stopColor="#6B8E9B" />
              <stop offset="1" stopColor="#647D89" />
            </linearGradient>
          </defs>
        </svg>
      </a>

      <button className="fixed top-[1.66666667vw] right-[1.66666667vw] z-50 text-[14px] leading-[21px] font-medium border border-zinc-100 px-[16px] py-[8px] rounded-[30px]">
        Contact us
      </button>

      {/* navigation */}
      <div className="nav text-[14px] leading-[21px] font-kanit text-[#FAFAFA] uppercase">
        <div className="nav__offset-container">
          <div className="nav__low-container space-x-[32px]">
            <div className="whitespace-normal">Introduce</div>
            <div className="whitespace-normal">About us</div>
            <div className="whitespace-normal">Features</div>
            <div className="whitespace-normal">Values</div>
            <div className="whitespace-normal">Ecosystem & Tokenomics</div>
            <div className="whitespace-normal">Roadmap</div>
          </div>
        </div>
      </div>
      {/* end of navigation */}

      <div
        className="screens h-screen max-h-screen relative z-10 overflow-hidden"
        onWheel={(e) => handleOnWheel(e)}
      >
        <div ref={el}>
          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center py-[87px] px-[7.5vw] ${
              activeSection === 0 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10">
              <div className="grid grid-cols-2">
                <div>
                  <h1 className="heading flex flex-col text-[102px] leading-[106px] mb-[16px] font-semibold">
                    <span className="text-gradient-blue-01">Livestream</span>
                    <span className="text-gradient-blue-01">Blockchain</span>
                  </h1>
                  <p className="text-fadein text-[28px] leading-[34px] mb-[29px] text-white font-kanit">
                    Fast. Seamless. Unconventional streaming and earning
                    platform
                  </p>

                  <button className="text-fadein bg-gradient-purple text-[16px] leading-[19px] px-[24px] py-[16px] rounded-[30px]">
                    About us
                  </button>
                </div>
              </div>
            </div>

            <ul className="flex flex-col items-center justify-center absolute right-[1.11vw] top-2/4 -translate-y-2/4	space-y-[21px]">
              <li>
                <a href="" title="">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M7.2353 18.6616C7.71055 18.9123 8.23985 19.0432 8.77715 19.043C10.5669 19.043 12.0279 17.6194 12.0939 15.845L12.1005 0H16.0538C16.0541 0.336542 16.0855 0.67234 16.1473 1.00316H13.2527V1.00371H17.2065C17.2059 2.32981 17.6866 3.61108 18.5592 4.60959L18.5604 4.61087C19.4506 5.1924 20.491 5.5016 21.5544 5.5006V6.3811C21.9265 6.4608 22.3113 6.50325 22.7071 6.50325V10.4576C20.7334 10.4599 18.809 9.84105 17.2065 8.68875V16.7234C17.2065 20.7355 13.9419 24 9.9293 24C8.93005 24.0002 7.9415 23.7941 7.0256 23.3944C6.11035 22.9951 5.28745 22.4112 4.60826 21.6792L4.60678 21.6782C2.73018 20.3606 1.5 18.1817 1.5 15.7202C1.5 11.7076 4.76453 8.4425 8.77715 8.4425C9.1053 8.44405 9.4329 8.46795 9.7578 8.51395V9.45005C9.78065 9.4496 9.80335 9.4488 9.82615 9.44805C9.86035 9.44685 9.89465 9.44565 9.9293 9.44565C10.2574 9.4472 10.585 9.4711 10.9099 9.5171V13.5534C10.5999 13.4561 10.2718 13.3995 9.9293 13.3995C9.0481 13.4005 8.2033 13.751 7.58025 14.3742C6.9572 14.9973 6.6068 15.8422 6.60595 16.7234C6.606 17.4193 6.82595 18.0975 7.23445 18.6611L7.2353 18.6616ZM3.13214 19.3199C3.46988 20.1998 3.9739 20.9981 4.60517 21.6765C3.96105 20.9872 3.46368 20.1855 3.13214 19.3199Z"
                      fill="url(#paint0_linear_890_4477)"
                    />
                    <defs>
                      <linearGradient
                        id="paint0_linear_890_4477"
                        x1="7.84526"
                        y1="9.58415"
                        x2="11.8389"
                        y2="24.073"
                        gradientUnits="userSpaceOnUse"
                      >
                        <stop stopColor="#EAC2FF" />
                        <stop offset="1" stopColor="#1945D9" />
                      </linearGradient>
                    </defs>
                  </svg>
                </a>
              </li>
              <li>
                <a href="" title="">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M2.35544 12.4614C4.20408 11.4431 6.26766 10.5933 8.19578 9.73904C11.5129 8.33991 14.8432 6.96502 18.207 5.68501C18.8615 5.46691 20.0375 5.25362 20.1528 6.22354C20.0897 7.59645 19.8299 8.96133 19.6518 10.3262C19.1996 13.3277 18.6769 16.3189 18.1672 19.3105C17.9916 20.307 16.7433 20.8228 15.9446 20.1851C14.0251 18.8885 12.0907 17.6046 10.1957 16.2779C9.57495 15.6471 10.1506 14.7413 10.705 14.2909C12.286 12.7328 13.9627 11.4091 15.461 9.77047C15.8652 8.79443 14.671 9.61701 14.2771 9.86905C12.1127 11.3606 10.0013 12.9431 7.71932 14.254C6.5537 14.8956 5.19515 14.3473 4.03006 13.9892C2.9854 13.5567 1.4546 13.121 2.35534 12.4615L2.35544 12.4614Z"
                      fill="url(#paint0_linear_890_4478)"
                    />
                    <defs>
                      <linearGradient
                        id="paint0_linear_890_4478"
                        x1="7.48924"
                        y1="11.4764"
                        x2="9.37348"
                        y2="20.8176"
                        gradientUnits="userSpaceOnUse"
                      >
                        <stop stopColor="#EAC2FF" />
                        <stop offset="1" stopColor="#1945D9" />
                      </linearGradient>
                    </defs>
                  </svg>
                </a>
              </li>
              <li>
                <a href="" title="">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M16.6711 15.4688L17.2031 12H13.875V9.75C13.875 8.8008 14.3391 7.875 15.8297 7.875H17.3438V4.92188C17.3438 4.92188 15.9703 4.6875 14.6578 4.6875C11.9157 4.6875 10.125 6.3492 10.125 9.35625V12H7.07812V15.4688H10.125V23.8547C10.7367 23.9508 11.3625 24 12 24C12.6375 24 13.2633 23.9508 13.875 23.8547V15.4688H16.6711Z"
                      fill="url(#paint0_linear_890_4482)"
                    />
                    <defs>
                      <linearGradient
                        id="paint0_linear_890_4482"
                        x1="10.1497"
                        y1="12.3997"
                        x2="14.9003"
                        y2="22.7678"
                        gradientUnits="userSpaceOnUse"
                      >
                        <stop stopColor="#EAC2FF" />
                        <stop offset="1" stopColor="#1945D9" />
                      </linearGradient>
                    </defs>
                  </svg>
                </a>
              </li>
              <li>
                <a href="" title="">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M11.4828 8.49023L11.5229 9.13903L10.8545 9.05958C8.4217 8.75505 6.2963 7.72228 4.49172 5.98775L3.60948 5.12711L3.38224 5.76266C2.90102 7.17941 3.20847 8.6756 4.21101 9.68189C4.7457 10.238 4.6254 10.3174 3.70305 9.98643C3.38224 9.8805 3.10153 9.80106 3.07479 9.84078C2.98122 9.93347 3.30204 11.1384 3.55601 11.615C3.90356 12.2771 4.61203 12.9259 5.38733 13.3098L6.04233 13.6144L5.26702 13.6276C4.51846 13.6276 4.49172 13.6409 4.57193 13.9189C4.83927 14.7795 5.89529 15.6932 7.07161 16.0904L7.90038 16.3684L7.17854 16.7921C6.10916 17.4012 4.85264 17.7455 3.59612 17.7719C2.99459 17.7852 2.5 17.8381 2.5 17.8779C2.5 18.0103 4.13081 18.7517 5.07988 19.043C7.92711 19.9037 11.309 19.5329 13.8488 18.0632C15.6534 17.0172 17.458 14.9384 18.3001 12.9259C18.7546 11.8534 19.2091 9.89374 19.2091 8.95366C19.2091 8.34459 19.2492 8.26514 19.9978 7.53691C20.4389 7.11321 20.8533 6.64978 20.9335 6.51738C21.0671 6.2658 21.0538 6.2658 20.372 6.4909C19.2358 6.88811 19.0754 6.83515 19.6368 6.23932C20.0512 5.81562 20.5458 5.04766 20.5458 4.82257C20.5458 4.78285 20.3453 4.84905 20.1181 4.96822C19.8775 5.10063 19.3428 5.29924 18.9417 5.4184L18.2199 5.64349L17.5649 5.20655C17.204 4.96822 16.696 4.70341 16.4287 4.62396C15.747 4.43859 14.7043 4.46507 14.0894 4.67693C12.4185 5.27275 11.3625 6.80867 11.4828 8.49023Z"
                      fill="url(#paint0_linear_890_4486)"
                    />
                    <defs>
                      <linearGradient
                        id="paint0_linear_890_4486"
                        x1="8.03529"
                        y1="10.4901"
                        x2="9.8872"
                        y2="19.8679"
                        gradientUnits="userSpaceOnUse"
                      >
                        <stop stopColor="#EAC2FF" />
                        <stop offset="1" stopColor="#1945D9" />
                      </linearGradient>
                    </defs>
                  </svg>
                </a>
              </li>
              <li>
                <a href="" title="">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M9.83545 11.9372C9.83545 11.3594 10.2512 10.8857 10.7779 10.8857C11.3045 10.8857 11.7295 11.3594 11.7203 11.9372C11.7203 12.515 11.3045 12.9886 10.7779 12.9886C10.2605 12.9886 9.83545 12.515 9.83545 11.9372ZM13.2072 11.9372C13.2072 11.3594 13.623 10.8857 14.1497 10.8857C14.6763 10.8857 15.0921 11.3594 15.0921 11.9372C15.0921 12.515 14.6763 12.9886 14.1497 12.9886C13.6322 12.9886 13.2072 12.515 13.2072 11.9372Z"
                      fill="url(#paint0_linear_890_4490)"
                    />
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M5.96187 3H18.4411C19.4934 3 20.3502 3.84642 20.3502 4.89524V21.4004L18.348 19.6524L17.2211 18.6219L16.0291 17.5271L16.5226 19.2291H5.96187C4.90952 19.2291 4.05273 18.3827 4.05273 17.3339V4.89524C4.05273 3.84642 4.90952 3 5.96187 3ZM14.2317 14.2699C14.5111 14.6196 14.8464 15.0152 14.8464 15.0152C16.9045 14.9508 17.6961 13.6167 17.6961 13.6167C17.6961 10.6543 16.3551 8.25302 16.3551 8.25302C15.014 7.2594 13.7381 7.287 13.7381 7.287L13.6078 7.4342C15.191 7.91261 15.9267 8.60263 15.9267 8.60263C14.9581 8.07821 14.0082 7.82061 13.1235 7.71941C12.453 7.64581 11.8104 7.66421 11.2423 7.73781C11.1935 7.73781 11.1518 7.74482 11.1049 7.75272C11.098 7.75387 11.0911 7.75504 11.084 7.75621C10.758 7.78381 9.96644 7.90341 8.96997 8.33582C8.62539 8.49222 8.42051 8.60263 8.42051 8.60263C8.42051 8.60263 9.19347 7.87581 10.8698 7.3974L10.7767 7.287C10.7767 7.287 9.5008 7.2594 8.15975 8.25302C8.15975 8.25302 6.8187 10.6543 6.8187 13.6167C6.8187 13.6167 7.60098 14.9508 9.65912 15.0152C9.65912 15.0152 10.0037 14.6012 10.2831 14.2515C9.10035 13.9019 8.65333 13.1659 8.65333 13.1659C8.65333 13.1659 8.74646 13.2303 8.91409 13.3223C8.9234 13.3315 8.93271 13.3407 8.95134 13.3499C8.96531 13.3591 8.97928 13.366 8.99325 13.3729C9.00722 13.3798 9.02119 13.3867 9.03516 13.3959C9.26798 13.5247 9.5008 13.6259 9.71499 13.7087C10.0968 13.8559 10.5532 14.0031 11.084 14.1043C11.7824 14.2331 12.602 14.2791 13.496 14.1135C13.9337 14.0399 14.3807 13.9111 14.8464 13.7179C15.1723 13.5983 15.5355 13.4235 15.9174 13.1751C15.9174 13.1751 15.4517 13.9295 14.2317 14.2699Z"
                      fill="url(#paint1_linear_890_4490)"
                    />
                    <defs>
                      <linearGradient
                        id="paint0_linear_890_4490"
                        x1="11.4083"
                        y1="11.7255"
                        x2="11.5401"
                        y2="13.0786"
                        gradientUnits="userSpaceOnUse"
                      >
                        <stop stopColor="#EAC2FF" />
                        <stop offset="1" stopColor="#1945D9" />
                      </linearGradient>
                      <linearGradient
                        id="paint1_linear_890_4490"
                        x1="8.92902"
                        y1="10.348"
                        x2="11.9846"
                        y2="21.46"
                        gradientUnits="userSpaceOnUse"
                      >
                        <stop stopColor="#EAC2FF" />
                        <stop offset="1" stopColor="#1945D9" />
                      </linearGradient>
                    </defs>
                  </svg>
                </a>
              </li>
            </ul>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center py-[87px] px-[7.5vw] ${
              activeSection === 1 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10">
              <div className="grid grid-cols-12">
                <div className="col-start-7 col-span-6">
                  <h4 className="btn-animate rounded-[38px] h-[35px] inline-flex items-center justify-center px-[18px] mb-[8px]">
                    <span className="circle"></span>
                    <span className="layer"></span>
                    <span className="txt whitespace-nowrap">ABOUT US</span>
                  </h4>
                  <h5 className="sub-heading text-gradient-blue text-[40px] mb-[32px] leading-[48px]">
                    A Cutting-edge <br />
                    multi-purpose SocialFi <br /> streaming platform
                  </h5>
                  <p className="desc text-[16px] leading-[24px] text-zinc-300 text-zinc-300">
                    In the era of high interactivity, edutainment, and a
                    combination between entertainment and earning, Vilik proudly
                    introduces a high-end video streaming platform built on the
                    BSC network. Inhere, content creators and consumers can both
                    play and earn cryptocurrency for their actions.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center justify-center py-[87px] px-[7.5vw] ${
              activeSection === 2 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10">
              <h5 className="sub-heading text-gradient-blue text-[40px] mb-[32px] leading-[48px] text-center">
                What is Vilik's network
              </h5>

              <div className="box bg-white-blur-003 px-[26px] pt-[13px] pb-[21px] max-w-[1224px] mx-auto">
                <img src="/network@2x.png" />
              </div>
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center py-[87px] ${
              activeSection === 3 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10 w-full">
              <div className="grid grid-cols-12 relative px-[7.5vw]">
                <div className="col-span-8">
                  <h5 className="sub-heading text-gradient-blue text-[40px] mb-[20px] leading-[48px]">
                    Features
                  </h5>
                  <p className="desc text-[16px] leading-[24px] mb-[40px] text-zinc-300 text-zinc-300">
                    Nowadays, other's platforms with a central data network are
                    based on centralised structures for the delivery of videos,
                    video storage, traffic, and routing are concentrated at the
                    central data network center. Besides that, these are
                    problems such as bandwidth issues on high traffic affecting
                    video quality and high cost of maintenance. To solve these
                    problems, Vilik Network is created to adopt a decentralized
                    P2P architecture, this network structure operates on the
                    same principle as BitTorrrent where users can share their
                    redundant computing and bandwidth resource as becoming the
                    nodes (peers) and are linked as distribution servers. This
                    innovative network architecture improves the quality of
                    stream delivery, and video resolution and reduces network
                    costs for bandwidth dramatically.
                  </p>
                </div>

                <div className="absolute w-[477px] right-[-28px] top-1/2 -translate-y-2/4">
                  <Moving yFrom={0} yTo={50} duration={10}>
                    <img src="/earth-layer-3.png" className="w-full h-auto" />
                  </Moving>
                </div>
              </div>

              <div className="w-full overflow-hidden pl-[7.5vw]">
                <Swiper
                  modules={[Navigation]}
                  slidesPerView="auto"
                  navigation
                  className="box features-slider"
                >
                  <SwiperSlide>
                    <div className="h-full bg-white-blur p-[32px] border-r-blur">
                      <div className="w-[56px] h-[56px] mb-[24px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/binancedex.png"
                          alt="Platform built on BSC Network"
                          width={30}
                          height={36}
                        />
                      </div>
                      <h6 className="text-[20px] leading-[28px] mb-[16px] font-semibold">
                        Platform built on BSC Network
                      </h6>
                      <p className="text-[#DCDCDC]">
                        The innovation generated by Vilik lies in the ecosystem
                        that combines the video live streaming function and
                        social media through the interaction with the newly born
                        crypto and VIK (crypto token).
                      </p>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className="h-full bg-white-blur p-[32px] border-r-blur">
                      <div className="w-[56px] h-[56px] mb-[24px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/stranger-duo.png"
                          alt="Stranger duo"
                          width={41}
                          height={23}
                        />
                      </div>
                      <h6 className="text-[20px] leading-[28px] mb-[16px] font-semibold">
                        Stranger duo
                      </h6>
                      <p className="text-[#DCDCDC]">
                        With Vilik&apos;s cryptocurrency wallet, you do not need
                        passwords or third-party servers to store digital
                        currency. We ensure high cybersafety and protect users
                        from DDoS with the PSD2 standard, which is identical to
                        European security
                      </p>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className="h-full bg-white-blur p-[32px]">
                      <div className="w-[56px] h-[56px] mb-[24px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/diamond.png"
                          alt="Diamond"
                          width={33}
                          height={35}
                        />
                      </div>
                      <h6 className="text-[20px] leading-[28px] mb-[16px] font-semibold">
                        Diamond
                      </h6>
                      <p className="text-[#DCDCDC]">
                        Diamond is the real value major unit in Vilik game
                        economy. It can be exchanged from VIK tokens, withdrawn
                        to the bank account at any time with low fee and fast
                        transaction.
                      </p>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className="h-full bg-white-blur p-[32px] border-r-blur">
                      <div className="w-[56px] h-[56px] mb-[24px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/wallet.png"
                          alt="Vilik's wallet"
                          width={30}
                          height={36}
                        />
                      </div>
                      <h6 className="text-[20px] leading-[28px] mb-[16px] font-semibold">
                        Vilik&apos;s wallet
                      </h6>
                      <p className="text-[#DCDCDC]">
                        Users do not need passwords or third-party servers to
                        store digital currency. Besides, we also ensure high
                        cyber safety with the DDoS with the PSD2 standard with a
                        combination of multisig transactions, automatically
                        enforced Two Factor Authentication.
                      </p>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className="h-full bg-white-blur p-[32px] border-r-blur">
                      <div className="w-[56px] h-[56px] mb-[24px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/mini-game.png"
                          alt="Mini-game"
                          width={33}
                          height={24}
                        />
                      </div>
                      <h6 className="text-[20px] leading-[28px] mb-[16px] font-semibold">
                        Mini-game
                      </h6>
                      <p className="text-[#DCDCDC]">
                        Our high anti-cheat with proxy and multiple account
                        detection systems offers the fair Vilik&apos;s Minigame/
                        Lucky game where users can play and earn diamonds
                        without being afraid of losing them or fraud activities.
                      </p>
                    </div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className="h-full bg-white-blur p-[32px]">
                      <div className="w-[56px] h-[56px] mb-[24px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/nft.png"
                          alt="NFT marketplace"
                          width={37}
                          height={28}
                        />
                      </div>
                      <h6 className="text-[20px] leading-[28px] mb-[16px] font-semibold">
                        NFT marketplace
                      </h6>
                      <p className="text-[#DCDCDC]">
                        Our NFT Marketplace is built to bring users unique and
                        exclusive products, such as unique photo frames, medals
                        with effects, and much more.
                      </p>
                    </div>
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center py-[87px] px-[7.5vw] ${
              activeSection === 4 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10 w-full">
              <div
                className="flex space-x-[40px] p-[8px] bg-white-blur-007 rounded-[30px] mb-[24px] max-w-[1002px] mx-auto"
                style={{
                  border: "1px solid rgba(255, 255, 255, 0.2)",
                }}
              >
                <button
                  type="button"
                  onClick={() => setActive("problem")}
                  className={`w-6/12 h-[43px] rounded-[22px] flex items-center justify-center ${
                    active === "problem"
                      ? "text-shadow-white-51 bg-white-012"
                      : ""
                  }`}
                >
                  Problem
                </button>
                <button
                  type="button"
                  onClick={() => setActive("solution")}
                  className={`w-6/12 h-[43px] rounded-[22px] flex items-center justify-center ${
                    active === "solution"
                      ? "text-shadow-white-51 bg-white-012"
                      : ""
                  }`}
                >
                  Solution
                </button>
              </div>

              {active === "problem" ? (
                <>
                  <h5 className="sub-heading text-center text-gradient-blue text-[24px] mb-[24px] leading-[38px]">
                    THE PROLEM OF LIVEVIDEO STREAMING TODAY
                  </h5>

                  <img
                    src="/problem@2x.png"
                    alt="THE PROLEM OF LIVEVIDEO STREAMING TODAY"
                    className="desc mx-auto w-full max-w-[844px] mb-[25px]"
                  />

                  <div className="box grid grid-cols-3 gap-x-[1px]">
                    <div className="flex h-auto p-[32px] mb-[16px] bg-white-blur">
                      <div className="w-[56px] h-[56px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/quality.png"
                          alt="Poor quality video"
                          width={26}
                          height={26}
                        />
                      </div>
                      <div className="pl-[24px] flex-1">
                        <h6 className="text-gradient-blue text-[20px] leading-[24px] mb-[16px] font-semibold">
                          Poor quality video
                        </h6>
                        <p className="text-[#DCDCDC]">
                          Due to inconvenience in CDN which causes re-buffering
                          video and high load times, users cannot enjoy perfect
                          quality in case of increasing demand for online video.
                        </p>
                      </div>
                    </div>
                    <div className="flex h-auto p-[32px] mb-[16px] bg-white-blur">
                      <div className="w-[56px] h-[56px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/data.png"
                          alt="Skyrocketing data needs"
                          width={23}
                          height={28}
                        />
                      </div>
                      <div className="pl-[24px] flex-1">
                        <h6 className="text-gradient-blue text-[20px] leading-[24px] mb-[16px] font-semibold">
                          Skyrocketing data needs
                        </h6>
                        <p className="text-[#DCDCDC]">
                          The demand for online media and entertainment has
                          rapidly increased, which means data needs are
                          skyrocketing with 4k, 8k and higher quality streams
                          creating an infrastructure bottleneck.
                        </p>
                      </div>
                    </div>
                    <div className="flex h-auto p-[32px] mb-[16px] bg-white-blur">
                      <div className="w-[56px] h-[56px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/system.png"
                          alt="Skyrocketing data needs"
                          width={44}
                          height={43}
                        />
                      </div>
                      <div className="pl-[24px] flex-1">
                        <h6 className="text-gradient-blue text-[20px] leading-[24px] mb-[16px] font-semibold">
                          A centralized and inefficient system
                        </h6>
                        <p className="text-[#DCDCDC]">
                          The centralized nature means less revenue flows back
                          to content creators and platforms.
                        </p>
                      </div>
                    </div>
                  </div>
                </>
              ) : null}

              {active === "solution" ? (
                <>
                  <h5 className="sub-heading text-center text-gradient-blue text-[24px] mb-[24px] leading-[38px]">
                    VILIK&apos;S SOLUTION
                  </h5>

                  <div className="desc relative mt-[54px]">
                    <img
                      src="/solution@2x.png"
                      alt="VILIK'S SOLUTION"
                      className="mx-auto w-full max-w-[683px] mb-[29px]"
                    />

                    {/* <svg
                      width="66"
                      height="3"
                      viewBox="0 0 66 3"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                      className="absolute top-[52px] left-[370px] w-[66px]"
                    >
                      <path
                        d="M0.345703 1.82715L65.9934 1.82715"
                        stroke="url(#paint0_linear_12_8563)"
                        strokeWidth="1.00996"
                        className="path path-1"
                      />
                      <defs>
                        <linearGradient
                          id="paint0_linear_12_8563"
                          x1="19.9878"
                          y1="2.22649"
                          x2="19.9902"
                          y2="2.87605"
                          gradientUnits="userSpaceOnUse"
                        >
                          <stop stopColor="#F07AFF" />
                          <stop offset="1" stopColor="#1945D9" />
                        </linearGradient>
                      </defs>
                    </svg>

                    <svg
                      width="66"
                      height="3"
                      viewBox="0 0 66 3"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                      className="absolute top-[52px] left-[542px] w-[66px]"
                    >
                      <path
                        d="M0.345703 1.82715L65.9934 1.82715"
                        stroke="url(#paint0_linear_12_8563)"
                        strokeWidth="1.00996"
                        className="path path-1"
                      />
                      <defs>
                        <linearGradient
                          id="paint0_linear_12_8563"
                          x1="19.9878"
                          y1="2.22649"
                          x2="19.9902"
                          y2="2.87605"
                          gradientUnits="userSpaceOnUse"
                        >
                          <stop stopColor="#F07AFF" />
                          <stop offset="1" stopColor="#1945D9" />
                        </linearGradient>
                      </defs>
                    </svg>

                    <svg
                      width="536"
                      height="166"
                      viewBox="0 0 536 166"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                      className="absolute top-[-27px] left-[217px] w-[536px]"
                    >
                      <rect
                        x="534.637"
                        y="0.504982"
                        width="164.624"
                        height="533.261"
                        rx="12.6363"
                        transform="rotate(90 534.637 0.504982)"
                        stroke="url(#paint0_linear_12_8558)"
                        strokeWidth="1.00996"
                        className="path path-1"
                      />
                      <defs>
                        <linearGradient
                          id="paint0_linear_12_8558"
                          x1="584.701"
                          y1="213.356"
                          x2="753.291"
                          y2="427.951"
                          gradientUnits="userSpaceOnUse"
                        >
                          <stop stopColor="#EAC2FF" />
                          <stop offset="1" stopColor="#1945D9" />
                        </linearGradient>
                      </defs>
                    </svg> */}
                  </div>

                  <div className="box grid grid-cols-3 gap-x-[1px]">
                    <div className="flex h-auto p-[32px] mb-[16px] bg-white-blur">
                      <div className="w-[56px] h-[56px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/data.png"
                          alt="Viewers earn rewards as VIK token"
                          width={29}
                          height={35}
                        />
                      </div>
                      <div className="pl-[24px] flex-1">
                        <h6 className="text-gradient-blue text-[20px] leading-[24px] mb-[16px] font-semibold">
                          Viewers earn rewards as VIK token
                        </h6>
                        <p className="text-[#DCDCDC]">
                          Viewers are now rewarded to participate in the
                          network. This is a new way of monetizing excess
                          network resources, such as bandwidth and storage.
                        </p>
                      </div>
                    </div>

                    <div className="flex h-auto p-[32px] mb-[16px] bg-white-blur">
                      <div className="w-[56px] h-[56px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/viewer.png"
                          alt="High quality, smoother video streaming"
                          width={29}
                          height={29}
                        />
                      </div>
                      <div className="pl-[24px] flex-1">
                        <h6 className="text-gradient-blue text-[20px] leading-[24px] mb-[16px] font-semibold">
                          High quality, smoother video streaming
                        </h6>
                        <p className="text-[#DCDCDC]">
                          Our decentralised network allows everyone to globally
                          earn streaming revenues. Herein, artists, producers,
                          streamers, and viewers jointly enjoy the most
                          immersive experiences.
                        </p>
                      </div>
                    </div>

                    <div className="flex h-auto p-[32px] mb-[16px] bg-white-blur">
                      <div className="w-[56px] h-[56px] flex items-center justify-center relative">
                        <svg
                          width="58"
                          height="58"
                          viewBox="0 0 58 58"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          className="w-full h-auto absolute top-0 left-0 animate-spin-slow"
                        >
                          <rect
                            x="0.5"
                            y="0.5"
                            width="57"
                            height="57"
                            rx="28.5"
                            stroke="url(#paint0_linear_13_423)"
                          />
                          <defs>
                            <linearGradient
                              id="paint0_linear_13_423"
                              x1="1"
                              y1="20.3589"
                              x2="55.6244"
                              y2="36.7546"
                              gradientUnits="userSpaceOnUse"
                            >
                              <stop stopColor="#1E1822" />
                              <stop offset="0.462674" stopColor="#EAC2FF" />
                              <stop offset="0.764757" stopColor="#1945D9" />
                              <stop offset="1" stopColor="#1E1822" />
                            </linearGradient>
                          </defs>
                        </svg>

                        <Image
                          src="/stream.png"
                          alt="Reduced cost of delivering video streams"
                          width={29}
                          height={29}
                        />
                      </div>
                      <div className="pl-[24px] flex-1">
                        <h6 className="text-gradient-blue text-[20px] leading-[24px] mb-[16px] font-semibold">
                          Reduced cost of delivering video streams
                        </h6>
                        <p className="text-[#DCDCDC]">
                          Fewer servers, less bandwidth and no more expensive
                          hosting mean more capital to invest in developing new
                          apps and improving the experience for users.c
                        </p>
                      </div>
                    </div>
                  </div>
                </>
              ) : null}
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center justify-center py-[87px] px-[7.5vw] ${
              activeSection === 5 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10">
              <div className="text-center">
                <h4 className="btn-animate large rounded-[38px] h-[35px] inline-flex items-center justify-center px-[18px] mb-[8px] relative z-10">
                  <span className="circle"></span>
                  <span className="layer"></span>
                  <span className="txt whitespace-nowrap">
                    ECOSYSTEM &amp; TOKENOMICS
                  </span>
                </h4>
              </div>

              <h5 className="sub-heading text-gradient-blue text-[40px] mb-[32px] leading-[48px] text-center">
                Impress user wiith exceptional features
              </h5>

              <div className="box bg-white-blur-003 px-[26px] pt-[13px] pb-[21px] max-w-[1209px] mx-auto">
                <img src="/network@2x.png" />
              </div>
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center justify-center py-[87px] px-[7.5vw] ${
              activeSection === 6 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10">
              <h5 className="sub-heading text-gradient-blue text-[40px] mb-[32px] leading-[48px] text-center">
                Monetary flow
              </h5>

              <div className="box bg-white-blur-003 px-[143px] py-[57px] w-full relative max-w-[1223px] mx-auto">
                <div className="absolute top-[-58px] left-[-19px]">
                  <Moving yFrom={10} yTo={-10} duration={5}>
                    <Image
                      src="/shape1@2x.png"
                      alt="NFT marketplace"
                      width={133}
                      height={133}
                    />
                  </Moving>
                </div>

                <img src="/monetary-flow@2x.png" />

                <div className="absolute bottom-[-131px] right-[-182px]">
                  <Moving yFrom={-10} yTo={10} duration={5}>
                    <Image
                      src="/shape2@2x.png"
                      alt="NFT marketplace"
                      width={277}
                      height={216}
                    />
                  </Moving>
                </div>
              </div>
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex flex-wrap items-center justify-center py-[87px] px-[7.5vw] ${
              activeSection === 7 ? "active" : ""
            }`}
          >
            <div className="screen__container relative z-10">
              <h5 className="sub-heading text-gradient-blue text-[40px] mb-[32px] leading-[48px] text-center">
                Tokenomics
              </h5>

              <div className="box text-[16px] leading-[24px] border-linear relative">
                <div className="absolute top-[-162px] right-[-173px] z-10">
                  <Moving yFrom={-10} yTo={10} duration={5}>
                    <Image
                      src="/shape3@2x.png"
                      alt="Tokenomics"
                      width={277}
                      height={216}
                    />
                  </Moving>
                </div>
                <div className="flex text-light-blue text-[18px] leading-[27px] bg-white-blur-015 divide-x divide-white/20 font-bold">
                  <div className="w-[156px] py-[8px] text-center">STAGE</div>
                  <div className="w-[156px] py-[8px] text-center">
                    % OF TOTAL SUPPLY
                  </div>
                  <div className="w-[156px] py-[8px] text-center">QUANTITY</div>
                  <div className="w-[156px] py-[8px] text-center">PRICE</div>
                  <div className="w-[156px] py-[8px] text-center">
                    TOTAL SOLD
                  </div>
                  <div className="flex-1 py-[8px] text-center">
                    VESTING PERIOD
                  </div>
                </div>

                <div className="divide-y divide-zinc-600">
                  {TOKENOMICS_DATA.map((item) => (
                    <div className="group" key={item.stage}>
                      <div className="flex transition-all group-hover:bg-zinc-800 divide-x divide-white/20">
                        <div className="w-[156px] py-[15px] text-center text-light-blue">
                          {item.stage}
                        </div>
                        <div className="w-[156px] py-[15px] text-center text-center">
                          <span className="inline-block rounded-[16px] py-[2px] px-[20px] border border-zinc-400 bg-zinc-800 text-[14px leading-[21px] font-medium">
                            {item.total}
                          </span>
                        </div>
                        <div className="w-[156px] py-[15px] text-center">
                          {item.quantity}
                        </div>
                        <div className="w-[156px] py-[15px] text-center">
                          {item.price}
                        </div>
                        <div className="w-[156px] py-[15px] text-center">
                          {item.totalSold}
                        </div>
                        <div className="flex-1 py-[15px] px-[20px]">
                          {item.vestingPeriod}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="flex text-[18px] leading-[27px] bg-white-blur-015 divide-x divide-white/20">
                  <div className="w-[156px] py-[8px] text-center font-bold">
                    TOTAL
                  </div>
                  <div className="w-[156px] py-[8px] text-center text-center">
                    <span className="inline-block py-[4px] px-[24px] rounded-[16px] text-center bg-gradient-pink-200">
                      100%
                    </span>
                  </div>
                  <div className="w-[156px] py-[8px] text-center text-light-blue">
                    100,000,000
                  </div>
                  <div className="w-[156px] py-[15px] text-center"></div>
                  <div className="w-[156px] py-[15px] text-center"></div>
                  <div className="flex-1 py-[15px] text-center"></div>
                </div>
              </div>
            </div>
          </div>

          <div
            className={`screen relative h-screen w-full flex  items-center justify-center py-[87px] px-[7.5vw] ${
              activeSection === 8 ? "active" : ""
            }`}
          >
            <div className="screen__container z-10">
              <div className="grid grid-cols-12">
                <div className="sub-heading col-span-4">
                  <div className="flex h-full items-center">
                    <div className="w-full grid grid-cols-2 gap-y-[20px]">
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-1"></span>
                        <span>28% Reward Pool</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-2"></span>
                        <span>3% Public Round</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-3"></span>
                        <span>10% Staking Pool</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-4"></span>
                        <span>5% Core Team</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-5"></span>
                        <span>12% Reserve</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-6"></span>
                        <span>3% Public Round</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-7"></span>
                        <span>10% Seed Round</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-8"></span>
                        <span>9% Liquidity</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-9"></span>
                        <span>6% Private Round</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-10"></span>
                        <span>10% Marketing</span>
                      </div>
                      <div className="flex items-center space-x-[16px]">
                        <span className="inline-block w-[20px] h-[20px] bg-linear-11"></span>
                        <span>4% Partnership</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="desc col-span-8">
                  <div className="text-right">
                    <img
                      className="inline-block w-full max-w-[682px] h-auto"
                      src="/chart.png"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="full-video">
        <video autoPlay playsInline muted loop>
          <source src="/iStockVideoHD_1306271041_min.mov" type="video/mp4" />
          Your browser does not support HTML5 video.
        </video>
      </div>
      <div className="overlay overlay-circle-0">
        <div className="pl-1"></div>
      </div>
      {/* overlay */}
      <div className="overlay-circle overlay-circle-1  absolute w-[35.069vw] h-[35.069vw] bg-blur-1 rounded top-[-3.88vw] left-[-9.58vw]"></div>
      <div className="overlay-circle overlay-circle-2 absolute w-[49.02vw] h-[46.31vw] bg-blur-2 rounded bottom-[-39.23vw] left-[-19.09vw]"></div>
      <div className="overlay-circle overlay-circle-3 absolute w-[47.57vw] h-[24.16vw] bg-blur-3 rounded bottom-[-18.47vw] right-[6.73vw]"></div>
      <div className="overlay-circle overlay-circle-4 absolute w-[49.30vw] h-[30.55vw] bg-blur-4 rounded top-[-21.18vw] right-[-18.88vw]"></div>

      <div className="overlay-circle overlay-circle-5 absolute w-[50.14vw] h-[55.21vw] bg-blur-5 rounded bottom-[-17.57vw] right-[-14.17vw]"></div>
      {/* end of overlay */}
    </main>
  );
}
