---
sections:
  -
    type: document
    cmscode: ixv6h3pzo
    path: content/our-team.md
    label: 'Our Team'
    template: our-team.yml
locales:
  - en
analytics_url:
upload_dir: static/uploads
email_to:
google_analytics_id:
google_tag_manager_id:
facebook_pixel_id:
microsoft_clarity_id:
webhook_url:
code: vilik
cmsCreatedAt: 1655982242
cmsUpdatedAt: 1655982242
cmsCreatedBy:
  email: hello@jamstackvietnam.com
  name: 'JAMstack Vietnam'
cmsUpdatedBy:
  email: hello@jamstackvietnam.com
  name: 'JAMstack Vietnam'
